include_guard(GLOBAL)
block()
  set(WITH_ZLIB off)
  set(CAPNP_LITE off)
  set(WITH_OPENSSL off)
  set(BUILD_TESTING off)
  find_package(capnproto)
  if(MSVC)
    target_link_libraries(kj Ws2_32)
  endif()
  add_library(capnproto::capnp ALIAS capnp)
endblock()
