include_guard(GLOBAL)
block()
  include(block_libpng.cmake)

  standard_executable(win-desktop WIN32)
  target_include_directories(win-desktop PUBLIC $<TARGET_PROPERTY:png_static,SOURCE_DIR>)
  target_include_directories(win-desktop PUBLIC $<TARGET_PROPERTY:png_static,BINARY_DIR>)
  target_link_libraries(win-desktop PRIVATE libpng::png_static)
  add_dependencies(win-desktop cl_files)
  if(USE_SPIRV)
    add_dependencies(win-desktop shaders)
  endif()
endblock()